import Head from 'next/head';
import Featured from '../components/featured/Featured';
import Navbar from '../components/navbar/Navbar';
import RecentBlogs from '../components/RecentBlogs/RecentBlogs';

import Blogs from '../components/blogs/Blogs';
import usePagination from '../utils/usePagination';
import InfiniteScroll from 'react-infinite-scroll-component';
import Loading from '../components/Loading/Loading';

const Home: React.FC = () => {
  const {
    isReachedEnd,
    flattedData,
    data,
    error,
    isLoading,
    isValidating,
    mutate,
    size,
    setSize,
  } = usePagination();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {/* Navbar */}

        {isLoading && <Loading />}
        {/* Featured Posts */}
        {data && (
          <>
            <Navbar />
            <Featured lastBlog={flattedData[0]} />
            {/* Recent Blogs */}
            <RecentBlogs otherBlogs={flattedData.slice(1, 6)} />
            {/* About Me */}
            <InfiniteScroll
              next={() => setSize(size + 1)}
              hasMore={!isReachedEnd}
              loader={<p>Loading</p>}
              endMessage={<p>Reached to the end</p>}
              dataLength={flattedData?.length}
            >
              <Blogs blogs={flattedData.slice(6)} />
            </InfiniteScroll>
          </>
        )}
        {/* {!isReachedEnd && (
          <button onClick={}>Load More</button>
        )} */}
      </main>
    </>
  );
};

export default Home;
